name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check unath file change
        run: |
          git diff --name-only origin/main...HEAD | grep terraform.tfvars
          if [ $? -eq 0 ]; then 
            echo "Unauth file change..Exiting"
          fi
