name: CI
on:
  push:
    branches: [ "main" ]
    paths: 
      - terraform.tfvars

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check unath file change
        run: | 
            echo "Changing terraform.tfvars file"